name: Release Packages (macOS)

on:
  workflow_dispatch:
  push:
    branches: [ "build/MacOS" ]
  pull_request:
    branches: [ "build/MacOS" ]

jobs:
  build_and_deploy:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: build/MacOS

      - uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: "1.86.0"
          platform_version: "15"

      - name: Cache cvc5 (~/.tau/cvc5)
        uses: actions/cache@v4
        with:
          path: ~/.tau/cvc5
          key: cvc5-v1-${{ runner.os }}
          restore-keys: |
            cvc5-v1-${{ runner.os }}-

      - name: MacOS build
        run: ./dev release
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          Boost_INCLUDE_DIR: ${{ steps.install-boost.outputs.BOOST_ROOT }}/include
          Boost_LIBRARY_DIRS: ${{ steps.install-boost.outputs.BOOST_ROOT }}/lib

      - name: Run tau
        run: ./build-Release/tau -v
