name: Release Packages (macOS)

on:
  workflow_dispatch:
  push:
    branches: [ "build/MacOS" ]
  pull_request:
    branches: [ "build/MacOS" ]

jobs:
  build_and_deploy:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: build/MacOS

      - uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: "1.86.0"

      - name: MacOS build
        run: ./dev release -DTAU_BUILD_TESTS=ON
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          Boost_INCLUDE_DIR: ${{ steps.install-boost.outputs.BOOST_ROOT }}/include
          Boost_LIBRARY_DIRS: ${{ steps.install-boost.outputs.BOOST_ROOT }}/lib

      - name: MacOS release tests
        run: ./dev test-release
