name: Release Packages (macOS)

on:
  workflow_dispatch:
  push:
    branches: [ "build/MacOS" ]
  pull_request:
    branches: [ "build/MacOS" ]

jobs:
  build_and_deploy:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: build/MacOS

      - name: MacOS release build
        run: ./dev release -DTAU_BUILD_TESTS=ON

      - name: MacOS release tests
        run: ./dev test-release
